pokemons = [
    #Normal Pokemon:
    'Eeve',
    'Rioulu',
    'Snover',
    'Absol',
    'Shelmet',
    'Honedge',
    'Aerodactyl',
    'Aron',
    'Aipom',
    'Abra',
    'Swablu',
    'Amura',
    'Foongus',
    'Mareep',
    'Anorith',
    'Ekans',
    'Growlithe',
    'Archen',
    'Spinirak',
    'Anorith']